language: node_js
node_js:
 - "13"
 
cache: npm

branches:
 only:
 - master

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

 
before_script:
 - npm install -g cordova ionic

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  
  keep_history: true
  on:
    branch: master
