dist: trusty
sudo: false


language: node_js
node_js:
 - "13"
 
cache:
  directories:
     - ./node_modules

branches:
 only:
 - master

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
 
install:
  - npm install
  
before_script:
 - npm install -g cordova ionic

script:
  - npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
  - npm run e2e -- --protractor-config=e2e/protractor-ci.conf.js

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master
